### ISSUE TITLE
Sign In Button Hides

### ISSUE THREAD

**Issue by mattbaseball** [GameFaceChat/GameFace#11]
So this is kind of a strange error. So to replicate it, you first go to sign-in and then type in an email address with an inaccurate password. There will be a notice stating that there is no user corresponding to the account and that it may be deleted (something similar to that). Then when you click the x and go back into register screen, and then back to the sign in screen, the sign in button is not showing (nor does it function if you press where the button was before).

**Comment by sriharivishnu** [comment]
Great Catch!

**Comment by sriharivishnu** [comment]
Fixed in Release 10
