### ISSUE TITLE
App Crashes When Quickly Allowing All Permissions

### ISSUE THREAD

**Issue by mattbaseball** [GameFaceChat/GameFace#15]
This only seems to happen on the first use after the initial install. However, when I quickly accept all permissions the app crashes. I've tried going into the settings, removing all permissions, and then accepting them again quickly, but the app performed as expected. Seems like this only occurs during the first opening of the app.

**Comment by mattbaseball** [comment]
This is on a Samsung Galaxy S9 with API 30. Only ever occurs on the first interaction with the app after it is done installing. It happens if you click open directly from the installer, or click done from the installer.

**Comment by sriharivishnu** [comment]
It caches the last user, and then database security prevents it from reading it from their data. Fixed in recent commit

**Comment by mattbaseball** [comment]
True didn't think about that as the cause. Good catch! Working now after testing on v0.0.8.
