### ISSUE TITLE
update app icon + create splash screen

### ISSUE THREAD

**Issue by sriharivishnu** [GameFaceChat/GameFace#3]

**Comment by sriharivishnu** [comment]
Which icon:
<img width="87" alt="Screen Shot 2020-05-04 at 2 50 03 PM" src="https://user-images.githubusercontent.com/37857112/81002028-9b0d8280-8e16-11ea-8c53-a17dd521a00a.png">
<img width="82" alt="Screen Shot 2020-05-04 at 2 48 18 PM" src="https://user-images.githubusercontent.com/37857112/81002029-9ba61900-8e16-11ea-9e11-a942556111de.png">

**Comment by mattbaseball** [comment]
Have added a shadow to the second option.
![Logo With Shadow](https://user-images.githubusercontent.com/64723868/81002644-972e3000-8e17-11ea-870e-e4ffe0a00685.jpg)

**Comment by mattbaseball** [comment]
Decided to add a shadow to the other logo as well.
![logo 13 Shadow](https://user-images.githubusercontent.com/64723868/81003410-da3cd300-8e18-11ea-8e97-46cf5ccc7b81.jpg)

**Comment by mattbaseball** [comment]
PNG version of controller with shadow
![logo 13 Shadow](https://user-images.githubusercontent.com/64723868/81004984-3f91c380-8e1b-11ea-8cbc-65297eb3736c.png)

**Comment by mattbaseball** [comment]
Attempt at a higher resolution png logo
![Higher Quality PNG](https://user-images.githubusercontent.com/64723868/81006970-6271a700-8e1e-11ea-9598-8b31bca1abe0.png)

**Comment by sriharivishnu** [comment]
added
