### ISSUE TITLE
Sign In with Google before registering

### ISSUE THREAD

**Issue by mattbaseball** [GameFaceChat/GameFace#9]
When attempting to sign in with google before the given account is registered, it displays a grey box on the bottom middle of the screen displaying "10:". There may be a space after the colon but it is somewhat difficult to tell. So will obviously need to change that message to notify the user why they are not signing in.

**Comment by sriharivishnu** [comment]
Should be fixed : Please confirm

**Comment by mattbaseball** [comment]
Great Fix! I like how you identify that they're a new user and bring them straight to the sign up screen with the username, bio, and everything.
